#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send "$(echo "Right click to update..." && cat /tmp/available-updates | head)" ;; 
    3) $TERMINAL -e pacupgrade ;;
esac

PACS=$(checkupdates | tee /tmp/available-updates | grep -c .)

if [ $PACS -gt 0 ] ; then 
    echo " $PACS"
    echo "$PACS"
    echo "#fabd2f"
fi
