#!/bin/sh
# Requires pulsemixer
case $BLOCK_BUTTON in
    1) pulsemixer --toggle-mute
esac

if [ $(pulsemixer --get-mute) -eq 1 ] ; then
    echo 
else
    pulsemixer --get-volume | awk '{print " "$1}'
fi
